### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by sasha4ox** [sasha4ox/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by dasha-korotkykh** [comment]
Хей :) тобі потрібно скласти свій блок з ти контактами або взяти їх з готового файлу, на який є посилання в тексті лекції. Знаєш де, чи скинути тобі лінку?

**Comment by sasha4ox** [comment]
Дякую, знайду)

**Comment by sasha4ox** [comment]
DONALD TRUMP
https://www.fb.com/DonaldTrump
realDonaldTrump@whitehouse.gov
https://twitter.com/realDonaldTrump
https://www.instagram.com/realDonaldTrump/
